//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.26 at 04:53:51 AM VET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.krux.com/selenium2-framework/elements.locators.map.schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mcgraw.test.automation.framework.selenium2.ui.locator.binding;
