//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-b35 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 07:55:19 AM VET 
//


package com.mcgraw.test.automation.framework.core.fixture.binding;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fixtureType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fixtureType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="JSON"/>
 *     &lt;enumeration value="SCRIPT"/>
 *     &lt;enumeration value="SQL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "fixtureType")
@XmlEnum
public enum FixtureType {

    JSON,
    SCRIPT,
    SQL;

    public String value() {
        return name();
    }

    public static FixtureType fromValue(String v) {
        return valueOf(v);
    }

}
