//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6-b35 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 07:55:19 AM VET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.krux.com/selenium2-framework/fixture.definition.schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mcgraw.test.automation.framework.core.fixture.binding;
